/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACE;

import DAO.AdminDAO;
import DTO.Admin;

/**
 *
 * @author 822131806
 */
public class CadastroAdm extends javax.swing.JFrame {

    /**
     * Creates new form PaginaAdm
     */
    public CadastroAdm() {
        initComponents();
        this.setTitle("CADASTRO");
        botaoCadastrar.setVisible(false);
        botaoConfirmar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelNascimento = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textNascimento = new javax.swing.JTextField();
        textCpf = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textSenha = new javax.swing.JTextField();
        botaoCancelar = new javax.swing.JButton();
        botaoConfirmar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        scrollPaneCadastro = new javax.swing.JScrollPane();
        textAreaCadastro = new javax.swing.JTextArea();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 460));
        setPreferredSize(new java.awt.Dimension(700, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 460));
        getContentPane().setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setText("INFORMAÇÕES PESSOAIS");
        getContentPane().add(labelTitulo);
        labelTitulo.setBounds(20, 0, 290, 40);

        labelNome.setText("Nome Completo:");
        getContentPane().add(labelNome);
        labelNome.setBounds(16, 45, 140, 20);

        labelNascimento.setText("Data de Nascimento:");
        getContentPane().add(labelNascimento);
        labelNascimento.setBounds(10, 60, 160, 70);

        labelCpf.setText("CPF:");
        getContentPane().add(labelCpf);
        labelCpf.setBounds(40, 130, 150, 30);

        labelTelefone.setText("Telefone:");
        getContentPane().add(labelTelefone);
        labelTelefone.setBounds(356, 46, 130, 30);

        labelEmail.setText("E-mail:");
        getContentPane().add(labelEmail);
        labelEmail.setBounds(360, 86, 100, 30);

        labelSenha.setText("Senha:");
        getContentPane().add(labelSenha);
        labelSenha.setBounds(360, 126, 100, 30);
        getContentPane().add(textNome);
        textNome.setBounds(130, 42, 199, 30);
        getContentPane().add(textNascimento);
        textNascimento.setBounds(130, 85, 199, 30);

        textCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfActionPerformed(evt);
            }
        });
        getContentPane().add(textCpf);
        textCpf.setBounds(130, 130, 199, 30);
        getContentPane().add(textTelefone);
        textTelefone.setBounds(420, 46, 198, 30);
        getContentPane().add(textEmail);
        textEmail.setBounds(420, 86, 198, 30);

        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textSenha);
        textSenha.setBounds(420, 126, 198, 30);

        botaoCancelar.setText("CANCELAR");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCancelar);
        botaoCancelar.setBounds(10, 340, 100, 40);

        botaoConfirmar.setText("CONFIRMAR");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfirmar);
        botaoConfirmar.setBounds(550, 340, 120, 30);

        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrar);
        botaoCadastrar.setBounds(550, 380, 120, 30);

        textAreaCadastro.setColumns(20);
        textAreaCadastro.setRows(5);
        scrollPaneCadastro.setViewportView(textAreaCadastro);

        getContentPane().add(scrollPaneCadastro);
        scrollPaneCadastro.setBounds(6, 196, 668, 140);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo Fullscreen.PNG"))); // NOI18N
        labelFundo.setText("jLabel8");
        getContentPane().add(labelFundo);
        labelFundo.setBounds(0, -14, 720, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void textCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        Admin adm = new Admin();
               
        adm.setNome(textNome.getText());
        adm.setNascimento(textNascimento.getText());
        adm.setCpf(textCpf.getText());
        adm.setTelefone(textTelefone.getText());
        adm.setEmail(textEmail.getText());
        adm.setSenha(textSenha.getText());
        
        AdminDAO ADAO = new AdminDAO();
        
        ADAO.inserir(adm);
        
        this.dispose();
        
        LoginAdm lAdm = new LoginAdm();
        lAdm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        botaoConfirmar.setVisible(true);
        
        String Nome;
        String Data;
        String Cpf;
        String Telefone;
        String Senha;
        String Email;
        
        Nome = textNome.getText();
        Data = textNascimento.getText();
        Cpf = textCpf.getText();
        Telefone = textTelefone.getText();
        Senha = textSenha.getText();
        Email = textEmail.getText();
        
        textAreaCadastro.selectAll();
        textAreaCadastro.replaceSelection("");
        
        textAreaCadastro.append("=================================\n");
        textAreaCadastro.append("Nome: "+ Nome + "\n");
        textAreaCadastro.append("Data de nascimento: " + Data + "\n" );
        textAreaCadastro.append("CPF: "+ Cpf + "\n");
        textAreaCadastro.append("Telefone: " + Telefone + "\n");
        textAreaCadastro.append("Senha: " + Senha + "\n" );
        textAreaCadastro.append("E-mail: " + Email + "\n");
        textAreaCadastro.append("================================\n");
        
        botaoCadastrar.setVisible(true);
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        PaginaAdm objPA = new PaginaAdm();
        objPA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelNascimento;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JScrollPane scrollPaneCadastro;
    private javax.swing.JTextArea textAreaCadastro;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNascimento;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSenha;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
