package INTERFACE;

import DTO.Admin;
import DAO.AdminDAO;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class LoginAdm extends javax.swing.JFrame {

    /**
     * Creates new form PaginaEntrar
     */
    public LoginAdm() {
        initComponents();
        this.setTitle("LOGIN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSenha1 = new javax.swing.JLabel();
        labelCpf1 = new javax.swing.JLabel();
        textCpf = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        labelLogo = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();
        botaoSouCliente = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        labelFundo = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        labelSenha1.setText("Senha:");
        getContentPane().add(labelSenha1);
        labelSenha1.setBounds(210, 260, 90, 50);

        labelCpf1.setText("CPF:");
        getContentPane().add(labelCpf1);
        labelCpf1.setBounds(210, 210, 90, 40);

        textCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfActionPerformed(evt);
            }
        });
        getContentPane().add(textCpf);
        textCpf.setBounds(290, 220, 191, 30);
        getContentPane().add(textSenha);
        textSenha.setBounds(290, 272, 190, 30);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginLogo.png"))); // NOI18N
        getContentPane().add(labelLogo);
        labelLogo.setBounds(210, 20, 400, 140);

        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEntrar);
        botaoEntrar.setBounds(320, 370, 120, 50);

        botaoSouCliente.setText("Sou cliente");
        botaoSouCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSouClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSouCliente);
        botaoSouCliente.setBounds(300, 490, 160, 23);

        labelLogin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelLogin.setText("OLÁ ADM, FAÇA SEU LOGIN!");
        getContentPane().add(labelLogin);
        labelLogin.setBounds(220, 140, 370, 80);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo Propaganda (1).PNG"))); // NOI18N
        getContentPane().add(labelFundo);
        labelFundo.setBounds(-10, -8, 770, 600);

        labelCpf.setText("CPF:");
        getContentPane().add(labelCpf);
        labelCpf.setBounds(210, 210, 90, 40);

        labelSenha.setText("Senha:");
        getContentPane().add(labelSenha);
        labelSenha.setBounds(210, 260, 90, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        Logar();

    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botaoSouClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSouClienteActionPerformed
        A1Login objLogin = new A1Login();
        objLogin.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoSouClienteActionPerformed

    private void textCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfActionPerformed

    }//GEN-LAST:event_textCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoSouCliente;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelCpf1;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSenha1;
    private javax.swing.JTextField textCpf;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables

    private void Logar() {
        try {
            String cpf, senha;

            cpf = textCpf.getText();
            senha = (textSenha.getText());

            Admin objA = new Admin();
            objA.setCpf(cpf);
            objA.setSenha(senha);

            AdminDAO objADAO = new AdminDAO();
            ResultSet rsADAO = objADAO.autenticacaoAdmin(objA);

            if (rsADAO.next()) {
                //chamar tela que eu quero abrir
                PaginaAdm pAdm = new PaginaAdm();
                pAdm.setVisible(true);
                this.dispose();

            } else {
                //enviar mensagem dizendo incorreto
                JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos");
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "PaginaEntrar" + erro);

        }

    }
}
