/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACE;

import DAO.PedidoDAO;
import DTO.Cliente;
import DTO.Pedido;
import DTO.Tenis;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class NikeJordan1 extends javax.swing.JFrame {

    /**
     * Creates new form Jordan1
     */
    public NikeJordan1() {
        initComponents();
        this.setTitle("NIKE AIR JORDAN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJordan = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        comboTamanho = new javax.swing.JComboBox<>();
        labelQuantidade = new javax.swing.JLabel();
        comboQuantidade = new javax.swing.JComboBox<>();
        labelCpf = new javax.swing.JLabel();
        textCpf = new javax.swing.JTextField();
        labelPagamento = new javax.swing.JLabel();
        comboPagamento = new javax.swing.JComboBox<>();
        botaoVoltar = new javax.swing.JButton();
        botaoFinalizarCompra = new javax.swing.JButton();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        labelJordan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nike2.jpeg"))); // NOI18N
        getContentPane().add(labelJordan);
        labelJordan.setBounds(177, 116, 377, 242);

        labelTitulo.setText("AIR JORDAN 1 LARANJA");
        getContentPane().add(labelTitulo);
        labelTitulo.setBounds(177, 21, 226, 38);

        labelTamanho.setText("Tamanho:");
        getContentPane().add(labelTamanho);
        labelTamanho.setBounds(855, 127, 68, 35);

        comboTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "38", "39", "40", "41" }));
        getContentPane().add(comboTamanho);
        comboTamanho.setBounds(941, 133, 72, 22);

        labelQuantidade.setText("Quantidade:");
        getContentPane().add(labelQuantidade);
        labelQuantidade.setBounds(857, 190, 80, 30);

        comboQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(comboQuantidade);
        comboQuantidade.setBounds(940, 192, 72, 30);

        labelCpf.setText("Informe seu CPF:");
        getContentPane().add(labelCpf);
        labelCpf.setBounds(830, 260, 110, 30);
        getContentPane().add(textCpf);
        textCpf.setBounds(940, 260, 130, 30);

        labelPagamento.setText("Forma de Pagamento:");
        getContentPane().add(labelPagamento);
        labelPagamento.setBounds(810, 320, 117, 50);

        comboPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIX", "Cartão de Crédito", "Cartão de Débito" }));
        getContentPane().add(comboPagamento);
        comboPagamento.setBounds(940, 330, 130, 30);

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(176, 549, 90, 39);

        botaoFinalizarCompra.setText("Finalizar Compra");
        botaoFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFinalizarCompra);
        botaoFinalizarCompra.setBounds(835, 549, 178, 39);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo Fullscreen.PNG"))); // NOI18N
        getContentPane().add(labelFundo);
        labelFundo.setBounds(-10, -10, 1220, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        NIKE n = new NIKE();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarCompraActionPerformed
        Cliente cli = new Cliente();
        Tenis ten = new Tenis();
        Pedido ped = new Pedido();

        cli.setCpf(textCpf.getText());
        ten.setMarca("Nike");
        ten.setModelo("Jordan 1");
        ten.setCor("Laranja");
        ten.setTamanho(comboTamanho.getSelectedItem().toString());
        ped.setQuantidade(Integer.parseInt(comboQuantidade.getSelectedItem().toString()));
        ten.setPreco((float) 200.50);
        ped.setPagamento(comboPagamento.getSelectedItem().toString());

        PedidoDAO PDAO = new PedidoDAO();

        PDAO.inserir(cli, ten, ped);
        
        JOptionPane.showMessageDialog(null, "OBRIGADO POR COMPRAR NA NOSSA LOJA!");
        
        PaginaCliente pc = new PaginaCliente();
        
        pc.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoFinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NikeJordan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFinalizarCompra;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboPagamento;
    private javax.swing.JComboBox<String> comboQuantidade;
    private javax.swing.JComboBox<String> comboTamanho;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelJordan;
    private javax.swing.JLabel labelPagamento;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textCpf;
    // End of variables declaration//GEN-END:variables
}
