/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACE;

import DAO.ClienteDAO;
import DTO.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class TabelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form ListaAdm
     */
    public TabelaCliente() {
        initComponents();
        consultarTabelaCliente();
        this.setTitle("TABELA DE CLIENTES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        botaoExcluir = new javax.swing.JToggleButton();
        botaoAlterar = new javax.swing.JToggleButton();
        botaoPreencher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        botaoCancelar = new javax.swing.JButton();
        labelCodigo = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textNascimento = new javax.swing.JTextField();
        labelNascimento = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        textCpf = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        textGenero = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        textSenha = new javax.swing.JTextField();
        labelRua = new javax.swing.JLabel();
        textRua = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        textBairro = new javax.swing.JTextField();
        labelComplemento = new javax.swing.JLabel();
        textComplemento = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        textCidade = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        textEstado = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        labelTitulo.setText("LISTA DE CLIENTES");
        getContentPane().add(labelTitulo);
        labelTitulo.setBounds(340, -110, 560, 300);

        botaoExcluir.setText("EXCLUIR");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(botaoExcluir);
        botaoExcluir.setBounds(1030, 360, 120, 50);

        botaoAlterar.setText("ALTERAR");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAlterar);
        botaoAlterar.setBounds(880, 360, 130, 50);

        botaoPreencher.setText("Preencher");
        botaoPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPreencherActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPreencher);
        botaoPreencher.setBounds(740, 360, 120, 50);

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "codigo", "nome", "nascimento", "cpf", "genero", "telefone", "rua", "numero", "bairro", "complemento", "cidade", "estado", "email", "senha"
            }
        ));
        jScrollPane1.setViewportView(tabelaCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 420, 1120, 240);

        botaoCancelar.setText("VOLTAR");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCancelar);
        botaoCancelar.setBounds(600, 360, 120, 50);

        labelCodigo.setText("Código:");
        getContentPane().add(labelCodigo);
        labelCodigo.setBounds(10, 50, 130, 16);

        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(textCodigo);
        textCodigo.setBounds(60, 50, 40, 22);

        labelNome.setText("Nome completo:");
        getContentPane().add(labelNome);
        labelNome.setBounds(10, 100, 140, 26);

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });
        getContentPane().add(textNome);
        textNome.setBounds(140, 100, 281, 30);

        textNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(textNascimento);
        textNascimento.setBounds(140, 150, 280, 30);

        labelNascimento.setText("Data de nascimento:");
        getContentPane().add(labelNascimento);
        labelNascimento.setBounds(10, 150, 150, 26);

        labelCpf.setText("CPF:");
        getContentPane().add(labelCpf);
        labelCpf.setBounds(20, 210, 110, 16);
        getContentPane().add(textCpf);
        textCpf.setBounds(140, 200, 281, 30);

        labelTelefone.setText("Telefone:");
        getContentPane().add(labelTelefone);
        labelTelefone.setBounds(10, 250, 120, 16);

        textTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(textTelefone);
        textTelefone.setBounds(140, 240, 281, 30);

        labelGenero.setText("Gênero:");
        getContentPane().add(labelGenero);
        labelGenero.setBounds(20, 280, 130, 30);

        textGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(textGenero);
        textGenero.setBounds(140, 280, 280, 30);

        labelEmail.setText("E-mail:");
        getContentPane().add(labelEmail);
        labelEmail.setBounds(20, 340, 120, 20);

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail);
        textEmail.setBounds(140, 330, 280, 30);

        labelSenha.setText("Senha:");
        getContentPane().add(labelSenha);
        labelSenha.setBounds(20, 390, 120, 16);

        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textSenha);
        textSenha.setBounds(140, 380, 280, 30);

        labelRua.setText("Rua:");
        getContentPane().add(labelRua);
        labelRua.setBounds(610, 100, 110, 30);
        getContentPane().add(textRua);
        textRua.setBounds(690, 100, 371, 30);

        labelBairro.setText("Bairro:");
        getContentPane().add(labelBairro);
        labelBairro.setBounds(610, 160, 110, 30);

        textBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBairroActionPerformed(evt);
            }
        });
        getContentPane().add(textBairro);
        textBairro.setBounds(690, 160, 370, 30);

        labelComplemento.setText("Complemento:");
        getContentPane().add(labelComplemento);
        labelComplemento.setBounds(600, 210, 100, 30);

        textComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textComplementoActionPerformed(evt);
            }
        });
        getContentPane().add(textComplemento);
        textComplemento.setBounds(690, 210, 370, 30);

        labelCidade.setText("Cidade:");
        getContentPane().add(labelCidade);
        labelCidade.setBounds(600, 260, 100, 30);

        textCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(textCidade);
        textCidade.setBounds(690, 260, 370, 30);

        labelEstado.setText("Estado:");
        getContentPane().add(labelEstado);
        labelEstado.setBounds(600, 310, 80, 30);

        textEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(textEstado);
        textEstado.setBounds(690, 310, 370, 30);

        labelNumero.setText("Número:");
        getContentPane().add(labelNumero);
        labelNumero.setBounds(1070, 100, 60, 30);

        textNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(textNumero);
        textNumero.setBounds(1120, 100, 50, 30);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo Fullscreen.PNG"))); // NOI18N
        getContentPane().add(labelFundo);
        labelFundo.setBounds(0, 0, 1910, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        PaginaAdm objPA = new PaginaAdm();
        objPA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNascimentoActionPerformed

    private void textTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefoneActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void textBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBairroActionPerformed

    private void textComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textComplementoActionPerformed

    private void textCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCidadeActionPerformed

    private void textNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroActionPerformed

    private void textGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textGeneroActionPerformed

    private void textEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEstadoActionPerformed

    private void botaoPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPreencherActionPerformed
        preencherCampos();
    }//GEN-LAST:event_botaoPreencherActionPerformed

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        alterarCliente();
        consultarTabelaCliente();
        limparCampos();
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        preencherCampos();
        excluirCliente();
        consultarTabelaCliente();
        limparCampos();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoAlterar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JToggleButton botaoExcluir;
    private javax.swing.JButton botaoPreencher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNascimento;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField textBairro;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textComplemento;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEstado;
    private javax.swing.JTextField textGenero;
    private javax.swing.JTextField textNascimento;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textRua;
    private javax.swing.JTextField textSenha;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables

    private void consultarTabelaCliente() {
        try {
            ClienteDAO CDAO = new ClienteDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaCliente.getModel();
            model.setNumRows(0);

            ArrayList<Cliente> lista = CDAO.ListarCliente();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getCodigo(),
                    lista.get(num).getNome(),
                    lista.get(num).getNascimento(),
                    lista.get(num).getCpf(),
                    lista.get(num).getGenero(),
                    lista.get(num).getTelefone(),
                    lista.get(num).getRua(),
                    lista.get(num).getNumero(),
                    lista.get(num).getBairro(),
                    lista.get(num).getComplemento(),
                    lista.get(num).getCidade(),
                    lista.get(num).getEstado(),
                    lista.get(num).getEmail(),
                    lista.get(num).getSenha()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showConfirmDialog(null, "consultarcliente: " + erro);
        }
    }

    private void preencherCampos() {
        int setar = tabelaCliente.getSelectedRow();

        textCodigo.setText(tabelaCliente.getModel().getValueAt(setar, 0).toString());
        textNome.setText(tabelaCliente.getModel().getValueAt(setar, 1).toString());
        textNascimento.setText(tabelaCliente.getModel().getValueAt(setar, 2).toString());
        textCpf.setText(tabelaCliente.getModel().getValueAt(setar, 3).toString());
        textGenero.setText(tabelaCliente.getModel().getValueAt(setar, 4).toString());
        textTelefone.setText(tabelaCliente.getModel().getValueAt(setar, 5).toString());
        textRua.setText(tabelaCliente.getModel().getValueAt(setar, 6).toString());
        textNumero.setText(tabelaCliente.getModel().getValueAt(setar, 7).toString());
        textBairro.setText(tabelaCliente.getModel().getValueAt(setar, 8).toString());
        textComplemento.setText(tabelaCliente.getModel().getValueAt(setar, 9).toString());
        textCidade.setText(tabelaCliente.getModel().getValueAt(setar, 10).toString());
        textEstado.setText(tabelaCliente.getModel().getValueAt(setar, 11).toString());
        textEmail.setText(tabelaCliente.getModel().getValueAt(setar, 12).toString());
        textSenha.setText(tabelaCliente.getModel().getValueAt(setar, 13).toString());

    }

    private void alterarCliente() {
        int codigo;
        String nome;
        String nascimento;
        String cpf;
        String genero;
        String telefone;
        String rua;
        String numero;
        String bairro;
        String complemento;
        String cidade;
        String estado;
        String email;
        String senha;

        codigo = Integer.parseInt(textCodigo.getText());
        nome = textNome.getText();
        nascimento = textNascimento.getText();
        cpf = textCpf.getText();
        genero = textGenero.getText();
        telefone = textTelefone.getText();
        rua = textRua.getText();
        numero = textNumero.getText();
        bairro = textBairro.getText();
        complemento = textComplemento.getText();
        cidade = textCidade.getText();
        estado = textEstado.getText();
        email = textEmail.getText();
        senha = textSenha.getText();

        Cliente cli = new Cliente();

        cli.setCodigo(codigo);
        cli.setNome(nome);
        cli.setNascimento(nascimento);
        cli.setCpf(cpf);
        cli.setGenero(genero);
        cli.setTelefone(telefone);
        cli.setRua(rua);
        cli.setNumero(numero);
        cli.setBairro(bairro);
        cli.setComplemento(complemento);
        cli.setCidade(cidade);
        cli.setEstado(estado);
        cli.setEmail(email);
        cli.setSenha(senha);

        ClienteDAO CDAO = new ClienteDAO();
        CDAO.alterarCliente(cli);
    }
    
    private void excluirCliente(){
        int codigo;
        
        codigo = Integer.parseInt(textCodigo.getText());
        
        Cliente cli = new Cliente();
        cli.setCodigo(codigo);
        
        ClienteDAO CDAO = new ClienteDAO();
        
        CDAO.excluirCliente(cli);
    }
    
    public void limparCampos(){
        textCodigo.setText("");
        textNome.setText("");
        textNascimento.setText("");
        textCpf.setText("");
        textGenero.setText("");
        textTelefone.setText("");
        textRua.setText("");
        textNumero.setText("");
        textBairro.setText("");
        textComplemento.setText("");
        textCidade.setText("");
        textEstado.setText("");
        textEmail.setText("");
        textSenha.setText("");
    }
}
